language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
      env: SYMFONY_VERSION=2.7.*
    - php: 7.2
      env: SYMFONY_VERSION=2.7.*
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.2
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.0.*
    - php: 7.2
      env: SYMFONY_VERSION=3.0.*
    - php: 7.1
      env: SYMFONY_VERSION=3.1.*@dev
    - php: 7.2
      env: SYMFONY_VERSION=3.1.*@dev
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*
    - php: 7.2
      env: SYMFONY_VERSION=4.0.*
    - php: 5.6
      env: ISOCODES_VERSION=2.1.*
    - php: 7.1
      env: ISOCODES_VERSION="dev-master"
  allow_failures:
    - php: nightly
    - php: hhvm
    - env: SYMFONY_VERSION=3.4.*@dev
    - env: SYMFONY_VERSION=4.0.*@dev
    - env: ISOCODES_VERSION="dev-master"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;

install:
  - composer global require phpunit/phpunit:@stable satooshi/php-coveralls:@stable codeclimate/php-test-reporter:@stable --no-update
  - composer global update --prefer-dist --no-interaction
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; PHPUNIT_OPTION="--testsuite symfony"; fi;
  - if [ "$SILEX_VERSION" != "" ]; then composer require "silex/silex:${SILEX_VERSION}" --no-update; PHPUNIT_OPTION="--testsuite silex"; fi;
  - if [ "$ISOCODES_VERSION" != "" ]; then composer require "ronanguilloux/isocodes:${ISOCODES_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;

script: phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml ${PHPUNIT_OPTION}

after_script:
  - coveralls -v
  - test-reporter
