language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.6.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 5.6
      env: SYMFONY_VERSION=3.1.*@dev
    - php: 5.6
      env: SILEX_VERSION=1.1.*
    - php: 5.6
      env: SILEX_VERSION=1.2.*
    - php: 5.6
      env: SILEX_VERSION=1.3.*
    - php: 5.6
      env: SILEX_VERSION="2.0.x-dev as 1.3"
    - php: 5.6
      env: ISOCODES_VERSION=1.2.*
    - php: 5.6
      env: ISOCODES_VERSION="dev-master"
  allow_failures:
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly
    - env: SILEX_VERSION="2.0.x-dev as 1.3"
    - env: SYMFONY_VERSION=3.1.*@dev
    - env: ISOCODES_VERSION="dev-master"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer selfupdate
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require phpunit/phpunit:@stable --no-update
  - composer global update --prefer-dist --no-interaction
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SILEX_VERSION" != "" ]; then composer require "silex/silex:${SILEX_VERSION}" --no-update; fi;
  - if [ "$ISOCODES_VERSION" != "" ]; then composer require "ronanguilloux/isocodes:${ISOCODES_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: make test

after_script:
  - php vendor/bin/coveralls -v
  - php vendor/bin/test-reporter
